### PR TITLE
changed link to extension-ideas repository

### PR DESCRIPTION
**Pull request by ivan-curkovic**

### CODE REVIEW

**Review by ajeetsraina — APPROVED** [review]
LGTM

**Comment by ivan-curkovic** [comment]
@ajeetsraina How can we change the "Submit Your Docker Extensions" link 👇?
image

**Comment by ajeetraina** [comment]
@ivan-curkovic You need to edit default.html file under https://github.com/collabnix/docker-community-extensions/blob/main/_layouts/

**Comment by ajeetraina** [comment]
@ivan-curkovic I will fix it for you.

**Comment by ivan-curkovic** [comment]
Thanks @ajeetraina

**Pull request merged**
